---
- additional_dependencies:
    - ./cmd
    - ./lib
  alias: dockerfmt
  args:
    - --write
    - --newline
    - --indent=4
    - --space-redirects
  description: Format Dockerfile files
  entry: dockerfmt
  files: ^.*(Container|Docker)file.*$
  id: dockerfmt
  language: golang
  name: dockerfmt
  pass_filenames: true
  require_serial: false
  exclude: ".dockerignore$"
  types_or:
    - dockerfile
